# Tareas para el rol de VM (Podman)

- name: Instalar dependencias para repositorio Podman
  ansible.builtin.apt:
    name:
      - software-properties-common
      - uidmap
    state: present
    update_cache: yes
  become: true

- name: Añadir repositorio oficial de Podman
  ansible.builtin.apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /"
    state: present
    filename: "devel:kubic:libcontainers:stable"
    update_cache: no
  become: true

- name: Importar clave GPG del repositorio Podman
  ansible.builtin.apt_key:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/Release.key"
    state: present
  become: true

- name: Instalar Podman
  ansible.builtin.apt:
    name: podman
    state: present
    update_cache: yes
  become: true

- name: Crear directorio /srv/webdata si no existe
  ansible.builtin.file:
    path: /srv/webdata
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copiar index.html personalizado
  ansible.builtin.copy:
    src: ../../../../applications/nginx-podman/content/index.html
    dest: /srv/webdata/index.html
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Ejecutar contenedor Nginx público
  containers.podman.podman_container:
    name: web
    image: "{{ acr_login_server }}/nginx-custom:{{ acr_image_tag }}"
    state: started
    ports:
      - "443:80"
    volume:
      - /srv/webdata:/usr/share/nginx/html
