
# Tareas para el rol de VM (Podman)

- name: Crear directorio /srv/webdata si no existe
  ansible.builtin.file:
    path: /srv/webdata
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copiar index.html personalizado
  ansible.builtin.copy:
    src: ../../../../applications/nginx-podman/content/index.html
    dest: /srv/webdata/index.html
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Instalar Podman
  ansible.builtin.apt:
    name: podman
    state: present
    update_cache: yes
  become: true

- name: Ejecutar contenedor Nginx público
  containers.podman.podman_container:
    name: web
    image: "{{ acr_login_server }}/nginx-custom:{{ acr_image_tag }}"
    state: started
    ports:
      - "443:80"
    volume:
      - /srv/webdata:/usr/share/nginx/html
