# Tareas para el rol de VM (Podman)

- name: Crear directorio /srv/webdata si no existe
  ansible.builtin.file:
    path: /srv/webdata
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Instalar Podman
  ansible.builtin.apt:
    name: podman
    state: present
    update_cache: yes
  become: true

- name: Login en ACR
  containers.podman.podman_login:
    registry: "{{ acr_login_server }}"
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"

- name: Descargar imagen seleccionada desde ACR
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/{{ acr_image_name }}:{{ acr_image_tag }}"
    state: present

- name: Ejecutar contenedor con la imagen seleccionada
  containers.podman.podman_container:
    name: web
    image: "{{ acr_login_server }}/{{ acr_image_name }}:{{ acr_image_tag }}"
    state: started
    ports:
      - "443:80"
    volume:
      - /srv/webdata:/usr/share/nginx/html
