# ansible/roles/vm/tasks/main.yml
---
- name: Actualizar la caché de paquetes del sistema
  ansible.builtin.apt:
    update_cache: yes

- name: Instalar Podman en la VM
  ansible.builtin.apt:
    name: podman
    state: present

- name: Obtener la contraseña del ACR desde Azure Key Vault
  set_fact:
    acr_password_from_vault: "{{ lookup('azure.azcollection.azure_keyvault_secret', acr_secret_name, vault_url=key_vault_url) }}"
  no_log: true

- name: Iniciar sesión en el ACR desde la VM usando el secreto del Key Vault
  containers.podman.podman_login:
    username: "{{ acr_username }}"
    password: "{{ acr_password_from_vault }}"
    registry: "{{ acr_login_server }}"
  no_log: true

- name: Desplegar el contenedor Nginx
  containers.podman.podman_container:
    name: nginx-webapp
    image: "{{ nginx_image }}"
    state: started
    ports:
      - "443:443"
    generate_systemd: true
    restart_policy: always

- name: Habilitar y arrancar el servicio del contenedor
  ansible.builtin.systemd:
    name: container-nginx-webapp.service
    enabled: yes
    state: started
    daemon_reload: yes