# Tareas para el rol de AKS

- name: Generar dockerconfigjson para ACR
  ansible.builtin.set_fact:
    acr_dockerconfigjson: >-
      {{
        {
          "auths": {
            acr_login_server: {
              "username": acr_username,
              "password": acr_password,
              "auth": (acr_username + ':' + acr_password) | b64encode
            }
          }
        } | to_json
      }}

- name: Crear namespace para la aplicación
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ app_namespace }}"

- name: Crear secreto para autenticación con ACR
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: acr-secret
        namespace: "{{ app_namespace }}"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ acr_dockerconfigjson | b64encode }}"

- name: Desplegar servicios principales (vote)
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'app_template.yml.j2') }}"
    namespace: "{{ app_namespace }}"
  vars:
    item: "{{ app.vote }}"

- name: Exponer la aplicación de voto con un LoadBalancer
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'service_template.yml.j2') }}"
    namespace: "{{ app_namespace }}"
  vars:
    item: "{{ app.vote }}"