---
all:
  vars:
    acr_login_server: "acre3uprdfi.azurecr.io"
    acr_username: "acre3uprdfi"
    nginx_image: "acre3uprdfi.azurecr.io/webapp:casopractico2"

vm:
  hosts:
    68.221.141.53:
      ansible_user: azureuser
      ansible_ssh_private_key_file: private_key.pem