---
- name: Instala Podman y ejecuta Nginx desde ACR
  hosts: vm
  become: true
  vars:
    nginx_image: "nginx-custom:latest"
  tasks:

    - name: Instalar dependencias para repositorio Podman
      apt:
        name:
          - software-properties-common
          - uidmap
        state: present
        update_cache: yes

    - name: Añadir repositorio oficial de Podman
      ansible.builtin.shell: |
        . /etc/os-release
        echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${ID}_${VERSION_ID}/ /" | tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${ID}_${VERSION_ID}/Release.key | apt-key add -
      args:
        warn: false

    - name: Actualizar caché de paquetes
      apt:
        update_cache: yes

    - name: Instalar Podman
      apt:
        name: podman
        state: present

    - name: Login en ACR
      containers.podman.podman_login:
        registry: "{{ acr_login_server }}"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"

    - name: Descargar imagen de Nginx personalizada
      containers.podman.podman_image:
        name: "{{ acr_login_server }}/{{ nginx_image }}"
        state: present

    - name: Ejecutar contenedor Nginx
      containers.podman.podman_container:
        name: nginx
        image: "{{ acr_login_server }}/{{ nginx_image }}"
        state: started
        ports:
          - "80:80"
