---
- name: Configuración y Despliegue General
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Descargar kubeconfig con az cli
      ansible.builtin.shell: |
        az aks get-credentials --resource-group {{ aks_resource_group }} --name {{ aks_cluster_name }} --overwrite-existing
      environment:
        AZURE_CONFIG_DIR: ~/.azure
      register: kubeconfig_result
      changed_when: false
      delegate_to: localhost

- name: Subida de imágenes a ACR
  hosts: localhost
  vars_files:
    - vault.yml
  roles:
    - acr

- name: Despliegue en VM con Podman
  hosts: vm
  become: true
  vars_files:
    - vault.yml
  roles:
    - vm

- name: Despliegue en AKS
  hosts: localhost
  vars_files:
    - vault.yml
  roles:
    - aks


