---
- name: 1. Preparar y subir la imagen al ACR
  hosts: localhost # Esta parte se ejecuta en tu propia máquina (WSL)
  vars_files:
    - secrets.yml
  
  roles:
    - role: acr

- name: 2. Desplegar Servidor Web en la VM con Podman
  hosts: vm # Esta parte se ejecuta en la máquina de Azure
  become: yes
  vars_files:
    - secrets.yml
  
  roles:
    - role: vm