---
- name: 1. Preparar y subir la imagen al ACR
  hosts: localhost # Se ejecuta en tu propia máquina (WSL)

  roles:
    - role: acr

- name: 2. Desplegar Servidor Web en la VM con Podman
  hosts: vm 
  become: yes 

  roles:
    - role: vm