
- name: Obtener kubeconfig de AKS con Azure CLI
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Descargar kubeconfig con az cli
      ansible.buil:tin.shell: |
        az aks get-credentials --resource-group rg-casopractico2 --name aks-casopractico2 --overwrite-existing
      environment:
        AZURE_CONFIG_DIR: ~/.azure
      register: kubeconfig_result
      changed_when: false



- name: Instala Podman en VM
  hosts: vm
  become: true
  vars_files:
    - vault.yml
  tasks:
    - name: Instalar dependencias para repositorio Podman
      apt:
        name:
          - software-properties-common
          - uidmap
        state: present
        update_cache: yes

    - name: Añadir repositorio oficial de Podman
      apt_repository:
        repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /"
        state: present
        filename: "devel:kubic:libcontainers:stable"
        update_cache: no

    - name: Importar clave GPG del repositorio Podman
      apt_key:
        url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/Release.key"
        state: present

    - name: Actualizar caché de paquetes
      apt:
        update_cache: yes

    - name: Instalar Podman
      apt:
        name: podman
        state: present

- name: Subida de imágenes a ACR
  hosts: localhost
  vars_files:
    - vault.yml
  roles:
    - acr

- name: Despliegue en VM con Podman
  hosts: vm
  become: true
  vars_files:
    - vault.yml
  roles:
    - vm

- name: Despliegue en AKS
  hosts: localhost
  vars_files:
    - vault.yml
  roles:
    - aks


